name: Manual Release and Publish

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release (e.g., 1.3.2)'
        required: true
        type: string
      release_notes:
        description: 'Release notes (optional)'
        required: false
        type: string
        default: 'This release includes the latest updates to the Kinde .NET SDK.'
      publish_to_nuget:
        description: 'Publish to NuGet.org'
        required: true
        type: boolean
        default: false

jobs:
  release:
    runs-on: ubuntu-latest
    # Restrict to specific users/organizations
    if: |
      github.actor == 'kinde-oss' ||
      github.actor == 'your-username' ||
      contains(github.actor, 'kinde')
    
    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
    
    - name: Restore dependencies
      run: dotnet restore
    
    - name: Build
      run: dotnet build --no-restore --configuration Release
    
    - name: Test
      run: dotnet test --no-build --verbosity normal --configuration Release
    
    - name: Update version in csproj
      run: |
        sed -i "s/<Version>.*<\/Version>/<Version>${{ github.event.inputs.version }}<\/Version>/" Kinde.Api/Kinde.Api.csproj
    
    - name: Pack
      run: dotnet pack Kinde.Api/Kinde.Api.csproj --configuration Release --output ./nupkgs --no-build
    
    - name: Create git tag
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add Kinde.Api/Kinde.Api.csproj
        git commit -m "Bump version to ${{ github.event.inputs.version }}"
        git tag -a "v${{ github.event.inputs.version }}" -m "Release version ${{ github.event.inputs.version }}"
        git push origin main
        git push origin "v${{ github.event.inputs.version }}"
    
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ github.event.inputs.version }}
        release_name: Release ${{ github.event.inputs.version }}
        draft: false
        prerelease: false
        body: |
          ## What's Changed
          
          ${{ github.event.inputs.release_notes }}
          
          ### 📦 NuGet Package
          The NuGet package is available at: `Kinde.SDK`
          
          ### 🔗 Links
          - [NuGet Package](https://www.nuget.org/packages/Kinde.SDK)
          - [Documentation](https://github.com/kinde-oss/kinde-dotnet-sdk)
          
          ### 📋 Changelog
          Please refer to the commit history for detailed changes.
    
    - name: Upload Release Assets
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./nupkgs/Kinde.SDK.${{ github.event.inputs.version }}.nupkg
        asset_name: Kinde.SDK.${{ github.event.inputs.version }}.nupkg
        asset_content_type: application/octet-stream
    
    - name: Publish to NuGet
      if: ${{ github.event.inputs.publish_to_nuget == 'true' }}
      run: dotnet nuget push ./nupkgs/Kinde.SDK.${{ github.event.inputs.version }}.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate
    
    - name: Publish Symbol Package
      if: ${{ github.event.inputs.publish_to_nuget == 'true' }}
      run: dotnet nuget push ./nupkgs/Kinde.SDK.${{ github.event.inputs.version }}.snupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate
      continue-on-error: true
