name: Publish to NuGet

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to publish (e.g., 1.3.2)'
        required: true
        type: string
      confirm_publish:
        description: 'Confirm you want to publish to NuGet.org'
        required: true
        type: boolean
        default: false

jobs:
  publish:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.confirm_publish == 'true' }}
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
    
    - name: Build and pack
      run: |
        dotnet restore
        dotnet build --configuration Release
        dotnet pack Kinde.Api/Kinde.Api.csproj --configuration Release --output ./nupkgs --no-build
    
    - name: Publish to NuGet
      run: dotnet nuget push ./nupkgs/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate
    
    - name: Publish Symbol Package
      run: dotnet nuget push ./nupkgs/*.snupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate
      continue-on-error: true
